{"name": "test_login_invalid_credentials", "status": "passed", "steps": [{"name": "Отправляем запрос на вход с неверными данными", "status": "passed", "start": 1732189665348, "stop": 1732189665692}, {"name": "Проверяем ошибку авторизации", "status": "passed", "start": 1732189665692, "stop": 1732189665692}], "start": 1732189665348, "stop": 1732189665692, "uuid": "2270eb21-ae8f-44bd-a1fd-d022b22065d4", "historyId": "03420e715c12f56e7e5c2808d1ca3a29", "testCaseId": "03420e715c12f56e7e5c2808d1ca3a29", "fullName": "tests.test_user_login.TestUserLogin#test_login_invalid_credentials", "labels": [{"name": "feature", "value": "Авторизация пользователя"}, {"name": "story", "value": "Неуспешный вход с неверными данными"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "WIN-SQET75TMPU5"}, {"name": "thread", "value": "5168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}